name: asalt
dependencies:
    - faunus=2.2
    - jupyterlab=3.3
    - matplotlib=3.3
    - notebook=4
    - numpy=1.19
    - pandas=1
    - python=3.6
    - scipy=1.5.3
    - nbformat=4.4
    - jupyter_client=7.1.0
    - jupyter_server=1.13.1
    - ruamel_yaml=0.15.80
    - yaml=0.2.5
    - jinja2=2.11.3
    - pygments=2.14.0

